using System;using System.IO;using System.Drawing;using System.Reflection;
internal static class PetCatalog {
 public static readonly string[] Names = {
  "Blanco clásico",
  "Naranjita",
  "Gris humo",
  "Negrito",
  "Crema",
  "Rosa pastel",
  "Lavanda",
  "Azul cielo",
  "Siamés",
  "Atigrado naranja",
  "Atigrado gris",
  "Calicó",
  "Esmoquin",
  "Karnalito (VALORANT)",
  "El Caballero (Hollow Knight)",
  "Hornet (Hollow Knight)",
  "Charmander",
  "Kirby",
  "Appa",
  "Eren Jaeger",
  "Toji Fushiguro",
  "Totoro",
  "TurboAbuela Gato",
  "Hatsune Miku",
  "Kasane Teto",
  "Among Us Rojo",
  "Barbaro",
  "Breach",
  "Brimstone",
  "Chamber",
  "Clove",
  "Cypher",
  "Duende Lanzadardos",
  "Fade",
  "Gekko",
  "Harbor",
  "Iso",
  "Jeff",
  "Jett",
  "KAYO",
  "Killjoy",
  "Miks",
  "Mini PEKKA",
  "Montapuercos",
  "Neon",
  "Omen",
  "Phoenix",
  "Raze",
  "Reyna",
  "Sage",
  "Tails",
  "Tejo",
  "Waylay",
  "Yoru"
 };
 public static readonly string[] Categories = {
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Otros",
  "Valorant",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Anime",
  "Anime",
  "Anime",
  "Anime",
  "Anime",
  "Otros",
  "Otros",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos",
  "Videojuegos"
 };
 public static readonly string[] Resources = {
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "pets.Videojuegos.Charmander.png",
  "pets.Videojuegos.Kirby.png",
  "pets.Anime.Appa.png",
  "pets.Anime.Eren_Jaeger.png",
  "pets.Anime.Toji_Fushiguro.png",
  "pets.Anime.Totoro.png",
  "pets.Anime.TurboAbuela_Gato.png",
  "pets.Otros.Hatsune_Miku.png",
  "pets.Otros.Kasane_Teto.png",
  "pets.Videojuegos.Among_Us_Rojo.png",
  "pets.Videojuegos.Barbaro.png",
  "pets.Videojuegos.Breach.png",
  "pets.Videojuegos.Brimstone.png",
  "pets.Videojuegos.Chamber.png",
  "pets.Videojuegos.Clove.png",
  "pets.Videojuegos.Cypher.png",
  "pets.Videojuegos.Duende_Lanzadardos.png",
  "pets.Videojuegos.Fade.png",
  "pets.Videojuegos.Gekko.png",
  "pets.Videojuegos.Harbor.png",
  "pets.Videojuegos.Iso.png",
  "pets.Videojuegos.Jeff.png",
  "pets.Videojuegos.Jett.png",
  "pets.Videojuegos.KAYO.png",
  "pets.Videojuegos.Killjoy.png",
  "pets.Videojuegos.Miks.png",
  "pets.Videojuegos.Mini_PEKKA.png",
  "pets.Videojuegos.Montapuercos.png",
  "pets.Videojuegos.Neon.png",
  "pets.Videojuegos.Omen.png",
  "pets.Videojuegos.Phoenix.png",
  "pets.Videojuegos.Raze.png",
  "pets.Videojuegos.Reyna.png",
  "pets.Videojuegos.Sage.png",
  "pets.Videojuegos.Tails.png",
  "pets.Videojuegos.Tejo.png",
  "pets.Videojuegos.Waylay.png",
  "pets.Videojuegos.Yoru.png"
 };
 public static bool HasAtlas(int design){return design>=0&&design<Resources.Length&&Resources[design]!=null;}
 public static Bitmap Load(int design){using(Stream stream=Assembly.GetExecutingAssembly().GetManifestResourceStream(Resources[design])){if(stream==null)throw new FileNotFoundException("Faltan los sprites de "+Names[design]);using(var source=new Bitmap(stream)){if(source.Width!=1024||source.Height!=512)throw new InvalidDataException("Hoja de sprites incompleta: "+Names[design]);return new Bitmap(source);}}}
}
